### PR TITLE
Added in the ability to do "random" posts

### PR DESCRIPTION
**Pull request by mlmurray**
I don't write nearly every day - this meant that often, even though I have "old posts" configured to be sent, I wasn't seeing any.

I added in code that if the current logic falls out the bottom (i.e. there was no old post on this day last year, last month, or last week) that it simply chooses a post at random.

Figure that's a feature that others may want, so I'm offering the code back.

### CODE REVIEW

**Comment by einaregilsson** [comment]
Thanks! I'll try to merge it in soon. There are a couple of things I'd want to change, I don't want to change the email check interval to 120 minutes, and I'd want to change the text in the email if it's a random post, e.g. instead of saying "Remember this? A (week|month|year) ago you wrote..." I'd want it to say "Remember this? On DATE you wrote...". But other than that it looks good, it will make it into the next release :+1:

**Comment by mlmurray** [comment]
Yeah - the 120 was me messing around but I couldn't figure out how to take
ghat out of my pull request. And totally agree on the change :)
On Mon, Apr 11, 2016 at 2:50 AM Einar Egilsson <notifications@github.com>
wrote:

> Thanks! I'll try to merge it in soon. There are a couple of things I'd
> want to change, I don't want to change the email check interval to 120
> minutes, and I'd want to change the text in the email if it's a random
> post, e.g. instead of saying "Remember this? A (week|month|year) ago you
> wrote..." I'd want it to say "Remember this? On DATE you wrote...". But
> other than that it looks good, it will make it into the next release [image:
> :+1:]
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/einaregilsson/MyLife/pull/10#issuecomment-208261876>
>
-- 
-- 
Sent from my Mobile Phone

**Comment by jonchui** [comment]
Hey @einaregilsson can you merge this in? Would be awesome to have in the release

**Comment by einaregilsson** [comment]
@jonchui Cool, I'll try to merge it in and get a release out sometime this week. Or maybe :)

Cool that you're still using this, I use it everyday and I know a couple of people used it at the beginning but I have no idea about how many people are actually using it day to day!

**Comment by einaregilsson** [comment]
Thanks, @mlmurray  and @jonchui  , this is now merged and released in version 1.3

**Pull request merged**
